#!/usr/bin/env bash
#
# © 2019 Match Group, LLC.
#
# GitQuery - Install Command Line Interface

scriptDir=$( cd "$(dirname "${BASH_SOURCE[0]}")" || exit 1 ; pwd -P )

cd "$scriptDir" || exit 1

./gradlew --quiet clean installDist

ln -sF $(pwd)/cli/build/install/cli/bin/cli /usr/local/bin/gitquery
