name: Bazel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
        id: java
      - uses: actions/checkout@v2
      - name: Build Deploy Jar
        run: bazelisk build //:GitQuery
