name: Gradle Samples
on:
  push:
    branches: [ main ]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build Samples
        run: |
          for d in samples/*; do
            set -e
            [ -d "$d" ] || continue
            echo "== $d =="
            pushd "$d" >/dev/null
            ../../gradlew gitQueryInit build
            popd >/dev/null
          done
